In [1]:
#Importação das bibliotecas
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

# Vamos conhecer mais um pouco sobre a biblioteca Numpy

Ferramentas de estruturas de dados

**criação array com 6 notas de 1 aluno**

In [2]:
#ARRAY 1 dimensão

notasAluno = np.array([5,4,3.1,2,5,8])
notasAluno

array([5. , 4. , 3.1, 2. , 5. , 8. ])

In [3]:
#Veja o tamanho 
notasAluno.shape

(6,)

Quando criamos o array chamado notasAluno ele carregava apenas as notas de um único aluno. Então você pode estar se perguntando, como faço para armazenar a nota de vários alunos?

Bom, para isso podemos utilizar um array com 2 dimensões:

In [4]:
notasPorAlunos = np.array([[10,20,3.5,10,5,9],[10,20,30,5,10,9],[20,20,40,9,1,10]])
notasPorAlunos

array([[10. , 20. ,  3.5, 10. ,  5. ,  9. ],
       [10. , 20. , 30. ,  5. , 10. ,  9. ],
       [20. , 20. , 40. ,  9. ,  1. , 10. ]])

In [5]:
notasPorAlunos.shape

(3, 6)

E se quisermos acompanhar os alunos desta turma durante 2 anos, como podemos armazenar estes dados?

Para isso, podemos utilizar um array de 3 dimensões:

In [6]:
notasPorAlunosPorAno=np.array([[[9,3,3,10,1,9],[5,20,3.5,10,5,8],[2,5,9,10,7,9]] , [[10,7,4,10,5,9],[9,20,7,10,5,9],[3,8,9,10,4,1]]])
notasPorAlunosPorAno

array([[[ 9. ,  3. ,  3. , 10. ,  1. ,  9. ],
        [ 5. , 20. ,  3.5, 10. ,  5. ,  8. ],
        [ 2. ,  5. ,  9. , 10. ,  7. ,  9. ]],

       [[10. ,  7. ,  4. , 10. ,  5. ,  9. ],
        [ 9. , 20. ,  7. , 10. ,  5. ,  9. ],
        [ 3. ,  8. ,  9. , 10. ,  4. ,  1. ]]])

In [7]:
notasPorAlunosPorAno.shape

(2, 3, 6)

# Vamos conhecer mais um pouco sobre a biblioteca Pandas

Ferramentas de análise de dados e estruturas de dados

**Estrutura de séries**: Uma Series é como um array 1D ou uma lista de valores. Toda Series possui um índice e os valores relacionados aos índices

Vamos então criar uma série com as notas de um aluno:

In [8]:
notasAlunosSeries = pd.Series([5,4,3.1,2,5,8])
notasAlunosSeries

0    5.0
1    4.0
2    3.1
3    2.0
4    5.0
5    8.0
dtype: float64

Podemos alterar os índices 0,1,2,3,4 e 5 para o título das notas (prova1, prova2, prova3, prova4, prova5 e prova6)

In [9]:
notasAlunosSeriesIndex = pd.Series([5,4,3.1,2,5,8], index=["prova 1", "prova 2", "prova 3", "prova 4", "prova 5", "prova 6"])
notasAlunosSeriesIndex

prova 1    5.0
prova 2    4.0
prova 3    3.1
prova 4    2.0
prova 5    5.0
prova 6    8.0
dtype: float64

Podemos recuperar todos os valores:

In [ ]:
#pega somente os valores
notasAlunosSeries.values

array([5. , 4. , 3.1, 2. , 5. , 8. ])

e também todos os índices:

In [ ]:
#analisa os índices. Começa em 0, tem 6 posições e as posições caminham de 1 em 1
notasAlunosSeries.index

RangeIndex(start=0, stop=6, step=1)

In [10]:
notasAlunosSeriesIndex.index

Index(['prova 1', 'prova 2', 'prova 3', 'prova 4', 'prova 5', 'prova 6'], dtype='object')

Quanto o aluno tirou na prova1?

In [ ]:
#recupera a nota relacionada ao indice prova 1
notasAlunosSeriesIndex["prova 1"]

5.0

Você já aprendeu como estruturar e recuperar dados de uma série. Agora vamos ver como podemos trabalhar com dataframes. Vale ressaltar que o dataframe permite criar uma tabela com observações e atributos (linhas e colunas).

In [ ]:
#cria o dataframe
df = pd.DataFrame({'Aluno' : ["João", "Maria", "Pedro", "Julia", "José"],
                  'Faltas' : [3,4,2,1,4],
                  'Nota Final' : [80.0,75.8,50.1,100.0,60.5]})
df

   Aluno  Faltas  Nota Final
0   João       3        80.0
1  Maria       4        75.8
2  Pedro       2        50.1
3  Julia       1       100.0
4   José       4        60.5

Para recuperar os índices, os quais ficam dispostos nas colunas,  basta acessar a função columns:

In [ ]:
df.columns

Index(['Aluno', 'Faltas', 'Nota Final'], dtype='object')

Se quiser ver os valores (nomes) de todos os alunos basta acessar o índice Alunos:

In [ ]:
df["Aluno"]

0     João
1    Maria
2    Pedro
3    Julia
4     José
Name: Aluno, dtype: object

Muitas vezes você receberá os dados em um arquivo no formato csv, excel, html e outros. Quando isso acontecer basta você carregar os dados deste aquivo para uma dessas estruturas. Se for uma tabela é mais comum carrega-los em um dataframe. Vamos ver um exemplo:

In [ ]:
#como ler um arquivo csv, e carrega-lo para m dataframe:
df = pd.read_csv("NomeAquivo.csv")
df